export default {
  // BACKEND
  FIREBASE: 'https://pyramid-tourney-tracker.firebaseio.com/test2',

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: 'ATTEMPTING_LOGIN',
	LOGIN_USER: 'LOGIN_USER',
	LOGOUT: 'LOGOUT',
  RESET_PROFILE: 'RESET_PROFILE',
  SET_PROFILE: 'SET_PROFILE',

	// AUTH STATES
	LOGGED_IN: 'LOGGED_IN',
	ANONYMOUS: 'ANONYMOUS',
	AWAITING_AUTH_RESPONSE: 'AWAITING_AUTH_RESPONSE',

  // TOURNAMENTS
  SET_TOURNAMENTS: 'SET_TOURNAMENTS'
}
