export default {
  // BACKEND
  FIREBASE: 'https://pyramid-tourney-tracker.firebaseio.com/test2',
  SET_FIREBASE_REF: 'SET_FIREBASE_REF',

  // AUTH ACTIONS
  ATTEMPTING_LOGIN: 'ATTEMPTING_LOGIN',
  CREATE_AND_LOGIN: 'CREATE_AND_LOGIN',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  SET_PROFILE: 'SET_PROFILE',
  RESET_PROFILE: 'RESET_PROFILE',
  SET_PROFILES: 'SET_PROFILES',

  // AUTH STATES
  LOGGED_IN: 'LOGGED_IN',
  ANONYMOUS: 'ANONYMOUS',
  AWAITING_AUTH_RESPONSE: 'AWAITING_AUTH_RESPONSE',

  // TOURNAMENTS
  SET_TOURNAMENTS: 'SET_TOURNAMENTS'
}
